### ISSUE TITLE
Better logger

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet#197]
Logging from the command line should be enabled on `--verbose` flag.

It should be formatted based on the selected output

**Comment by ValentinTrinque** [comment]
With hindsight, it's easier to ouput logs in dedicated log files, instead of output as it's hard to conciliate with the normal output.

**Comment by ValentinTrinque** [comment]
This will be addressed when #127 is merged

**Comment by gordsport** [comment]
@ValentinTrinque 
Is this still a requirement?

**Comment by ValentinTrinque** [comment]
It's being worked on with the API v2. Closing.
