### ISSUE TITLE
Unable to untaint a key using API

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vegawallet#304]
Scenario: API call to untaint a key

Actual Result: Response 404 - page not fund error
Expected: Key should be successfully untainted

```
Action is =  LOCALWALLET-UNTAINTKEY 

URL Built =  http://127.0.0.1:1789/api/v1/keys/f4a6c8e968d92cd74b7593be6d540028c70ae3091db866368ab6503b7dee9b8d/untaint
Header Built with Valid User Access Token !!!
Payload Built =  {"passphrase":"Douglas@123"}
API Call Type =  PUT
API Response Status =  404
API Response =  404 page not found
```

**Comment by gordsport** [comment]
@MuthuVega and @ValentinTrinque to discuss with @candida-d to see if we should bring this work into the sprint

**Comment by ValentinTrinque** [comment]
After discussing it with @jeremyletang, we agreed that the CLI should be the only "gateway" to manage the wallets, and the API should only expose endpoints that allow data retrieval or transaction signing.
