### ISSUE TITLE
Fix or remove colour codes on Windows

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/vegawallet#333]
OUTPUT from the binary windows wallet looks like this 

```
←[32;31m➜ ←[0m←[31mImportant←[0m

←[32;36m➜ ←[0m←[36mRun the service←[0m
```

ref https://discord.com/channels/720571334798737489/732949310198644897/903296922092191765

**Comment by ValentinTrinque** [comment]
We should add the ability to disable the color all together for all plateforms

**Comment by vega-paul** [comment]
@MuthuVega Could you test this on windows o/s

**Comment by jgsbennett** [comment]
Happy that this fix is good, although have raised two more issues for Windows vegawallet:
https://github.com/vegaprotocol/vegawallet/issues/436
https://github.com/vegaprotocol/vegawallet/issues/437
