### ISSUE TITLE
Upgrading from 0.9-pre wallet does not appear to download config with fairground/testnet 

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/vegawallet#343]
Reported via Discord: 

We think that the community member previously had 0.9-pre wallet installed and upgraded to 0.9.2, and relayed the following error detail:

```
If I type ./vegawallet network list, then, No network registered
It seems that I need to use ./vegawallet network import <specific name or url?> but not sure how the network should be specified 
```

They can download and install the config manually by using the following:

```
./vegawallet network import --from-file "[yourpath/devnet.toml]"
```

with the file located here:

https://github.com/vegaprotocol/vegawallet/blob/develop/network/defaults/fairground.toml

Normally this config is pulled in directly when calling `vegawallet init`, suspect this doesn't happen for those that have certain 0.9-pre release binaries.

**Comment by MuthuVega** [comment]
Doing a `vegawallet init -f ` will resolve the issue for users upgrading from 0.9-pre wallets to 0.9.2 wallet , this will automatically pullin and create the fairground network config file

**Comment by ValentinTrinque** [comment]
I created an issue to introduce a command that will make things clearer 👍🏻 
- #346

**Comment by ValentinTrinque** [comment]
> this will automatically pullin and create the fairground network config file

Just to mention that the default network configuration are not pulled in. They are embedded in the binary.
