### ISSUE TITLE
Unsupported output is not properly caught

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet#369]
When using an unsupported output, the error verification is not properly done and result in escaping the error message display.

https://github.com/vegaprotocol/vegawallet/blob/a32cd1838438bef69e70ea0138e993049783a307/cmd/cmd.go#L33-L35

For this condition to work, the `InvalidOutputError` should contain any unpredictable value such as the wrapped error message.

**Comment by MuthuVega** [comment]
Tested OK on latest wallet

```
Muthus-MBP:repos muthupandianvadivelu$ vegawallet -o muthu network list
unsupported output

```
