### ISSUE TITLE
Renaming a wallet file makes it impossible to log into it

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet#371]
Because we store the wallet name in the file, if the latter is renamed, the filename and the wallet name are not in sync anymore, which makes it impossible to load as the origin of the name we use to identify a wallet changes in the code base. Sometime, filname, sometime wallet name.

**Comment by ValentinTrinque** [comment]
The problem came from the fact the wallet name was used as a filename and was also set in the file. Renaming the file caused the filename and the file content out of sync. So we decided to remove the wallet name from the serialisation, to only retrieve it from the filename. As a result, renaming the file would rename the wallet.

**Comment by MuthuVega** [comment]
Tested OK on latest wallet

Created a new wallet, renamed the physical wallet file , then tried to list the wallet and works OK.

```
root@35838827cce9:/workspace/beehive/behave/features/go-wallet# ./vegawallet_linux_arm list
- TestWallet1
root@35838827cce9:/workspace/beehive/behave/features/go-wallet# cd /root/.local/share/vega/wallets/
root@35838827cce9:~/.local/share/vega/wallets# ls
TestWallet1
root@35838827cce9:~/.local/share/vega/wallets# mv TestWallet1 TestRenamedWallet1
root@35838827cce9:~/.local/share/vega/wallets# cd /workspace/beehive/behave/features/go-wallet/
root@35838827cce9:/workspace/beehive/behave/features/go-wallet# ./vegawallet_linux_arm list
- TestRenamedWallet1
root@35838827cce9:/workspace/beehive/behave/features/go-wallet# ./vegawallet_linux_arm info --wallet TestRenamedWallet1
Enter passphrase: 

Type:
HD wallet
Version:
2
ID:
a32ba6011742d6e850d6953c132e099f45d1b8731c074b1f7adda512f9593bdb
root@35838827cce9:/workspace/beehive/behave/features/go-wallet# 

```
