### ISSUE TITLE
Consider architecture for fetching config files

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/vegawallet#374]
As a:
* non-technical end user who is not very familiar with command-line arguments; _or_
* a semi-technical end user who is ok with reading docs and following instructions; _or_
* an expert use who wants access to all possibilities

I want to be able to:
* easily fetch a Mainnet / Fairground / _other_ network config from somewhere
* ensure the fetched config file is up to date and correct

I understand I can already:
* `vegawallet network import --from-file PATH_TO_NETWORK`
* `vegawallet network import --from-url URL_TO_NETWORK`

but
* What if the network validator list changes, and my local one is now out of date?
* What if I'm using an old release of `vegawallet`?
* What if I run `vegawallet network import --from-url URL_TO_NETWORK` today on one machine, then tomorrow I run the same command on a different machine, and now my 2 machines act differently (because different files were downloaded). How can I tell that these machines are configured differently?

## See also
* #346
* #373

## Discussion
* Should new commandline commands/args be added?
* Should any  commandline commands/args be removed?
* (from @davidsiska-vega) "_If someone was to hijack the network config source and pointed many user wallets to a rogue network, could they do anything nefarious with it?_" ([Slack thread](https://vegaprotocol.slack.com/archives/C01P24880JY/p1636974000291100?thread_ts=1636721058.200300&cid=C01P24880JY))
* Other questions in comments, please.

**Comment by ValentinTrinque** [comment]
If the embedded network configuration functionality is only going to be used for fairground, I would rather get rid of it, as `network import` can do the job just fine, and will avoid us extra work, and slim down the codebase
