### ISSUE TITLE
Incorrect version number in the output for key generate and key describe command

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vegawallet#379]
Scenario: Generate a new key for a new wallet and then use the key describe command to get details of the key

Expected: The algorithm version should be displayed as 2 
Actual: The algorithm version should be displayed as 2 

Note: This is an issue with the key generate and key describe commands ONLY

Examples:

Generate a new key for a new wallet:

```
ACTION =  WALLET-CLI-GENERATEKEYS
Call Type =  Command Line
CLI Command Built =  vegawallet -o json key  generate  -w  TEST-Alk7u  -p  ./go-wallet/pass.txt 2>&1 | tee ./go-wallet/output.txt 
CLI Output = 
{"wallet":{"name":"TEST-Alk7u","filePath":"/Users/muthupandianvadivelu/Library/Application Support/vega/wallets/TEST-Alk7u","mnemonic":"dumb secret gesture limit chimney brown coyote unhappy plug where recycle zebra mother able ride enable brass ask car brain seek defy maid coffee"},"key":{"keyPair":{"privateKey":"d67075367e407f97e6ac4db05e74c0a64a6fb75c92553aef09bd68a4596a4bed74a0375de1b144f49ba137b9748a7f0a9851793d3a34743a18c8db26543b5b05","publicKey":"74a0375de1b144f49ba137b9748a7f0a9851793d3a34743a18c8db26543b5b05"},"algorithm":{"name":"vega/ed25519","version":1},"meta":[{"key":"name","value":"TEST-Alk7u key 1"}]}}
```

Describe the above key for the wallt:

```
ACTION =  WALLET-CLI-KEYDESCRIBE
Call Type =  Command Line
CLI Command Built =  vegawallet -o json key  describe  -w  TEST-Alk7u  -p  ./go-wallet/pass.txt  -k  74a0375de1b144f49ba137b9748a7f0a9851793d3a34743a18c8db26543b5b05 2>&1 | tee ./go-wallet/output.txt 
CLI Output = 
{"publicKey":"74a0375de1b144f49ba137b9748a7f0a9851793d3a34743a18c8db26543b5b05","algorithm":{"name":"vega/ed25519","version":1},"meta":[{"key":"name","value":"TEST-Alk7u key 1"}],"isTainted":false}
```

**Comment by ValentinTrinque** [comment]
AFAIU, you expect the version of the algorithm to be `2` instead of `1`. However, it should be `1`. The version `2` is the wallet version.

**Comment by wwestgarth** [comment]
I believe the wallet version and the key's algorithm version are two different things.

The wallet version determines how the key is derived i.e the creation of the EC key.  The key's version is actually the algorithm version, and is the version of the edDSA algorithm used.

**Comment by ValentinTrinque** [comment]
@wwestgarth, that’s right.

**Comment by MuthuVega** [comment]
@ValentinTrinque - It was just that the version numbers for wallet and keys were a bit confusing , if the key version should be 1 , then its correct - so assume no change is required.
Happy to close bug is we agree.

**Comment by ValentinTrinque** [comment]
Cool ! Thanks for the feedback. An improvement has been shipped, feel free to test it ans open a new issue if it's not satisfactory.
