### ISSUE TITLE
Add token dApp to network configuration

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/vegawallet#408]
Some browsers on some operating systems (difficult to pin down exactly what) will not allow connections from https sites to localhost via http. 

Meaning that connecting a website e.g. https://token.vega.xyz to your local wallet can be difficult. This is why the `--console-proxy` option exists and why there is a line in a network config to define where "Console" lives for that network.

However, Console isn't the only thing that people will want to connect from.

Suggestion: allow the user to specify any url (as well as have a default in the network config.
```bash
machine:~ me$ ./vegawallet service run -n fairground -p https://token.fairground.wtf
```
-----
Bonus: In some cases I may wish to connect to more than one URL. I'm not sure if something like this is a goer?

```bash
machine:~ me$ ./vegawallet service run -n fairground -p https://token.fairground.wtf, https://console.fairground.wtf
```

**Comment by ValentinTrinque** [comment]
Why not adding this to the network configuration, so we have a set of "tools" that is proxy'd ?

**Comment by campbellssource** [comment]
That works for me too.
