### ISSUE TITLE
Improve help text in CLI

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vegawallet#412]
- [x] **key untaint** help, add copy warning about untainting: If you tainted a key for security reasons, you should not untaint it.
- [x] **sign** help, fix spelling, replace with: Sign a blob of data base64 encoded
- [x] **force** description, update to: Overwrite exiting wallet configuration at the specified path
- [x] **command**: Include information on how to form a command 
- [x] **command send** example, update to: Send a command with a maximum of 10 retries
- [x] **delete** help, update to "Delete a given wallet, which removes the wallet file and deletes the wallet name and password." (this may need more work)  
- [x] **key annotate**, this could be described more clearly: The metadata is a list of key-value pairs. *A key-value is colon-separated, and the key-values are comma-separated.*
- [x] **network**, help: This description could use a little more info, maybe some examples of how to use it / related flags?
- [x] **tx**: Can this help text be expanded on for more context? "Provides utilities for interacting with transactions" 
- [x] **version**: How about adding guidance in the helper text about the difference between the 'release version' and the 'wallet version'? Currently says: Get the version of the program.

**Comment by ValentinTrinque** [comment]
I updated the wallet import section to add some details about the passphrase, as well.

**Comment by ValentinTrinque** [comment]
> key untaint help, add copy warning about untainting: If you tainted a key for security reasons, you should not untaint it.

It's in the long description. For the short description, it might be too long.

> - command: Include information on how to form a command

It's already done in the description of `command send` 
```
The command should be a Vega command formatted as a JSON payload, as follows:

'{"commandName": {"someProperty": "someValue"} }'

For vote submission, it will look like this:

'{"voteSubmission": {"proposalId": "some-id", "value": "VALUE_YES"}}'
```

> delete help, update to "Delete a given wallet, which removes the wallet file and deletes the wallet name and password." (this may need more work)

I trimmed it for the short description but added more details in the long description.

> network, help: This description could use a little more info, maybe some examples of how to use it / related flags?

Not sure which command you are referring to. If this is just `network` bear in mind this is not a command executing anything, it's cosmetic, it's just to scope / group `network` related action-commands.

> Can this help text be expanded on for more context? "Provides utilities for interacting with transactions"

Same as the `network` comment.

> version: How about adding guidance in the helper text about the difference between the 'release version' and the 'wallet version'? Currently says: Get the version of the program.

Added more context to the long description. I also renamed the `program` to `software` which, hopefully, might ring more bells.

**Comment by candida-d** [comment]
> > * command: Include information on how to form a command
> 
> It's already done in the description of `command send`
> > > I know this exists in the available sub-commands list, but it could be extra-helpful to let people know that they should interact with 'command send' as the description of 'command' alone isn't going to help guide someone to make the most useful choice, it feels like a dead-end description. 

> > network, help: This description could use a little more info, maybe some examples of how to use it / related flags?
> 
> Not sure which command you are referring to. If this is just `network` bear in mind this is not a command executing anything, it's cosmetic, it's just to scope / group `network` related action-commands.
> 
> > Can this help text be expanded on for more context? "Provides utilities for interacting with transactions"
> 
> Same as the `network` comment.
> 
> > > I think here, as well, a bit more guidance that this is just a cosmetic command and that people should try interacting with the other commands within it would be helpful to send people along the right path.

**Comment by ValentinTrinque** [comment]
So should we add some kind of documentation for basic `key`, `network`,  `command`, `service` and `tx` on these commands ?

**Comment by candida-d** [comment]
@ValentinTrinque My inclination is yes, but I would say that. :) I think each command having a little more info about what it can do / how to do it is like laying out breadcrumbs. But not explaining every command in every other command, though I don't think you're suggesting that.

**Comment by ValentinTrinque** [comment]
Yes I agree. Ok so do you think you could provide to tutorial content that would make sense from a beginner perspective, and based on what we have on the doc website ?

**Comment by candida-d** [comment]
Probably not straightaway, but with some help, sure. That being said, I still think a little bit of extra text in each helper section is reasonable without teaching the whole thing via CLI - an in-between step.
