### ISSUE TITLE
[OSX] Binary release should be signed

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vegawallet#42]
It's possible to run the current release (0.4.2) on OSX, but the end user has to fiddle with security settings to allow running unsigned binaries. This isn't the end of the world, but life would be easier if it was signed in such a way that OSX was happy to run it.

# Tasks
- [ ] Add signing process to OSX build

# References
- https://github.com/git-lfs/git-lfs/pull/4143/commits/bfc5304edf2b218fb8abf22aba02b5dc7e842a4a
- https://developer.apple.com/developer-id/
- https://docs.revenera.com/installanywhere2017/Content/helplibrary/OSX-GetCert.htm

**Comment by candida-d** [comment]
What about for Windows? 

And Linux is fine as-is, right?

**Comment by ashleyvega** [comment]
Current status: Waiting for Apple to provide a certificate. @jambone23 is watching and waiting... :hourglass:
