### ISSUE TITLE
Help find/change wallet config

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/vegawallet#430]
Occasionally users will want to change an existing network config e.g. add or remove GRPC hosts.

importing again isn't ideal as the may wish to make one change rather than create new and remove old.

I don't mind if it is a command to update, a command to list networks including path to config or something else.

**Comment by ValentinTrinque** [comment]
The easiest will be to help locate the file, as implementing "text management" using the CLI is just too painful in this case.

**Comment by ValentinTrinque** [comment]
You are going to introduce a new command `vegawallet network locate`
