### ISSUE TITLE
Notarize MacOS binary

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet#438]

**Comment by gordsport** [comment]
Parking for a later sprint as higher priority work happening first

**Comment by gordsport** [comment]
Re-closing as we now have open issues:
- https://github.com/vegaprotocol/vegawallet/issues/464
- https://github.com/vegaprotocol/vegawallet/issues/465

as per: https://vegaprotocol.slack.com/archives/C02KSKW6Y3F/p1643380968823969
