### ISSUE TITLE
Action confirmation prompt doesn't work on windows

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet#439]
When running the command:
```sh
vegawallet delete --wallet WALLET
```

the user is asked to confirm his request. On windows, the confirmation message fails to be recognized.

This is probably because windows is adding a `\r` in the response that is not stripped before comparaison.

**Comment by jgsbennett** [comment]
Confirm that I can see both the broken behaviour before the fix, and the the command working with the fix on the PR branch. Output for the two commands before/after as follows:

> C:\dev\vega\go-wallet>vegawallet delete --wallet TEST3
> ✗ You are running an unreleased version of the Vega wallet (v0.12.0+dev). Use it at your own risk!
> 
> Are you sure? (y/n) y
> 
> ✗ invalid answer, expect "yes" or "no"
> 
> C:\dev\vega\go-wallet>vegawallet delete --wallet TEST3
> ✗ You are running an unreleased version of the Vega wallet (v0.12.0+dev). Use it at your own risk!
> 
> Are you sure? (y/n) yes
> 
> ✗ invalid answer, expect "yes" or "no"
> 
> C:\dev\vega\go-wallet>vegawallet delete --wallet TEST3
> ✗ You are running an unreleased version of the Vega wallet (v0.12.0+dev). Use it at your own risk!
> 
> Are you sure? (y/n) y
> 
> ✓ Wallet TEST3 deleted
Tested on c138f13e2f2d63e226c6a48117913ce7380a57f2 on Windows 10, using Command Prompt, PowerShell and Git Bash (Git Bash worked before and after the fix).
