### ISSUE TITLE
Endpoint for if there is a new version

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet#474]
# Motivation

We want users to keep their wallets up to date. We do this by notifying on the CLI if there is a new version available. It would be good to show this on the FE without having to reimplement all the logic, to ensure the check is consistent. This check already exists in the CLI and has some cool features built in around pre release and dev versions.

# Requirements

```
POST /version/check
```

Which returns the new version and URL if there is a version for the user to update to.

[Slack ref](https://vegaprotocol.slack.com/archives/C02KSKW6Y3F/p1643634917002149)

Related: https://github.com/vegaprotocol/token-frontend/issues/1172

**Comment by ValentinTrinque** [comment]
That would be nice if this endpoint could return information about the software in use, not just the CLI, since it's the same service that is running on the CLI and the GUI

**Comment by ValentinTrinque** [comment]
@dexturr I was thinking, shouldn't we let the software I charge of this checking, now it's built in it, everywhere ?

**Comment by ValentinTrinque** [comment]
@dexturr I have been thinking. I think we shouldn't do this. The FE should be "backend" agnostic, and the update message should be left to app responsibility. We can't ignore the fact some people may want to reimplement this service entirely. The API you are using should be fixed once and for all and that's it. FE should only rely on API versioning and not specific tools.

I am even thinking about removing the version endpoint entirely. 

What do you think ?

**Comment by dexturr** [comment]
Sounds reasonable, this made sense when we only had a command line wallet however with desktop/CLI/possible browsers it makes sense for the apps themselves to handle this. 

I think the motivation was if there was functionality only wallet version X and above supported then it would be nice to show this to a user on the frontend "this is not going to work". However I think your assessment is correct.

Kill it :+1:
