### ISSUE TITLE
Transfer command not recognised / failing in wallet

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vegawallet#501]
The transfer command is not recognised by wallet and is failing when trying to submit a transfer request via wallet

Wallet Transfer Req

`{'transfer': {'fromAccountType': 'ACCOUNT_TYPE_GENERAL', 'toAccountType': 'ACCOUNT_TYPE_GENERAL', 'to': '785efd78a0c65067ea8e0efe287ecdf22da63a66fa8fcbd4bc30dabf8b007b97', 'asset': '70760e9d4f485c8938b7ca2b66bd931cf9424436a8849209000f8797b3a0b42a', 'amount': '1000', 'reference': 'Test Transfer', 'oneOff': {'deliverOn': '500'}}}
`

Wallet Error Response 

`{"errors":{"input_data.command":["is not supported"]}}`

**Comment by MuthuVega** [comment]
@ValentinTrinque is aware of this issue.

**Comment by jeremyletang** [comment]
Have you updated your wallet to a recent version?

**Comment by MuthuVega** [comment]
Yes, wallet has been updated , spoke to @ValentinTrinque earlier and he acknowledged that this is an issue.

**Comment by jeremyletang** [comment]
> Yes, wallet has been updated , spoke to @ValentinTrinque earlier and he acknowledged that this is an issue.

alright I figured as well, sending a PR now.
