### ISSUE TITLE
Add and endpoint to the wallet-service to check transactions

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vegawallet#524]
Now that a core node supports [CheckTransaction](https://github.com/vegaprotocol/protos/blob/develop/sources/vega/api/v1/core.proto#L27) we should add an equivalent endpoint to the vega wallet service, `/api/v1/command/check` for example. 

This will pass the check-request onto core and will enable a nice workflow where people can do things like:
```
req = "some transaction"
url = f"{wallet_server_url}/api/v1/command/check"
response = requests.post(url, headers=headers, json=req)
assert response.ok

# send it for real now we now its ok
url = f"{wallet_server_url}/api/v1/command/sync"
response = requests.post(url, headers=headers, json=req)
```

**Comment by ValentinTrinque** [comment]
Why would we want this when the `/api/v1/command/sync` endpoint already do this ?

**Comment by wwestgarth** [comment]
Because if `sync` is successful the transaction gets added to the mempool. `CheckTransaction` does not add the transaction to the mempool, it just checks that it would.

**Comment by ValentinTrinque** [comment]
That I understand. The thing I want to know is, what's the use case ? Why would we want that on the wallet ?

**Comment by jeremyletang** [comment]
Because you want to be able to check if the transaction will pass the mempool checktx call, will it be reject for any reason like spam protection, or anything.
