### ISSUE TITLE
Couldn't register the windows file sink

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet#569]
New upgrade to cli-wallet 0.15.0 on windows 10.

Error:

```
Couldn't register the windows file sink: sink factory already registered for scheme "winfile"
```

**Comment by cdm** [comment]
<img width="538" alt="windows-0-15-0-sinkfile-error" src="https://user-images.githubusercontent.com/149245/169877523-0bb51236-928b-4c88-8165-90cbdb28c7b1.png">
