### ISSUE TITLE
Old version of wallet recommended upgrade version leaves wallet incompatible with mainet

### ISSUE THREAD

**Issue by ettec** [vegaprotocol/vegawallet#579]
When using an old version of CLI wallet, it recommends that you upgrade the version to latest which maybe incompatible with mainnet (caught me out!).

**Comment by jeremyletang** [comment]
Well, I think we advise them to download the last version released yes. And if you go to the release page, the last version release which is not a pre-release is the 0.13.2, which is the same used by the desktop wallet.

When a new version of the node is deployed on mainnet, wallet version compatible with it will be switch to be a non pre-release version anymore.
