### ISSUE TITLE
Add OpenAPI definition generation from wallet REST API

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/vegawallet#6]
To support our quest for excellent docs, ideally we'd need to revisit the wallet service API and create a swagger definition file that can be used to create API documentation. The definition of the service is currently listed in the repo README as:

> Vega Wallet can also host a REST-ish interface to make itself available for local and remote clients. This can be used to make keys available to web-based Vega clients, for example Vega Console.

I've found this package that could help us significantly as we're REST only on this binary:

https://github.com/swaggo/swag

> Swag converts Go annotations to Swagger Documentation 2.0. We've created a variety of plugins for popular Go web frameworks. This allows you to quickly integrate with an existing Go project (using Swagger UI).

We could use this package to do most of the work in CI or build and just put definitions on the code 💥 

Bonus points: I'd like to optionally check/clean up the REST endpoints/urls shape.

**Comment by ValentinTrinque** [comment]
Closing it due to stale status. Feel free to re-open it.

**Comment by edd** [comment]
Notes from a conversation between me, @ValentinTrinque & @mattrussell36 

This library would get us OpenAPI v3 support:
- https://github.com/getkin/kin-openapi

This would get us v2:
- https://goswagger.io/generate/spec.html

**Comment by pscott31** [comment]
Don't we already do this, or am I missing something?

e.g.

[https://github.com/vegaprotocol/protos/tree/develop/swagger](https://github.com/vegaprotocol/protos/tree/develop/swagger)

**Comment by gordsport** [comment]
reopening as this relates to the api for the vega wallet.

to be re-reviewed and prioritised

**Comment by edd** [comment]
See https://github.com/vegaprotocol/vega/issues/5618
