### ISSUE TITLE
Improve the way we serve the console

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vegawallet#67]
# Problem

https://testnet.vega.trading is served using HTTPS. Running the wallet locally serves the wallet APIs over HTTP, and browsers generally do not allow mixed content, and thus refuse to connect to the wallet running locally

# Workaround

`vegawallet` has an option to work around this, `vegawallet service run -p`, which opens a browser window and will allow connecting to the local wallet. The way this works is untidy though - it runs an HTTP proxy that 'serves' the console on a local http server, which then means the browser will connect to the HTTP wallet. It's a bit of a fudge, but it works.

# Potential solutions
We could:
1. Build console in to vega-wallet and serve it locally
    - This means we need to build a new release when console releases, or build some update mechanism to update the JS bundle
2. Build an basic UI that hosts console and wallet in it's own 'app'
    - This gives people a bit less flexibility about which web3 extension they use

**Comment by candida-d** [comment]
"Create account" feature exists on Console (at least staging). 

For this to be possible, there will need to be 2 applications for Windows, one that runs through command line, and one that doesn't. But perhaps it's better to just release 2 for each OS.

**Comment by gordsport** [comment]
Closing as this will be removed
