### ISSUE TITLE
[Windows] Binary release should be signed

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vegawallet#93]
Windows Defender, the security layer in Windows, blocks running the Vega Wallet. Sometimes it's possible to get around it, and sometimes it's not, leaving users stuck. 

Here is a report from one user: https://vega-testnet.nolt.io/70 

It needs to be signed so that users can actually use it, and so that it doesn't look sketchy. 

_Originally posted by @candida-d in https://github.com/vegaprotocol/go-wallet/issues/42#issuecomment-816617619_

## Process
- purchase a software-signing certificate
- add private key (and certificate?) as Github CI secret
- add process in CI to sign `go-wallet.exe`
- publish the signed `exe` instead of (in addition to?) the unsigned one

## Refs
- http://www.ab-weblog.com/en/digitally-sign-binary-files-on-windows/
- [ksoftware.net: What are the differences between OV and EV level code signing certificates?](https://support.ksoftware.net/support/solutions/articles/232500-what-are-the-differences-between-ov-and-ev-level-code-signing-certificates-)
- **OV** - Organisation Validation
- **EV** - Extended Validation ("require 2FA, meaning they are distributed on an encrypted hardware device that is required for signing" [ref](https://support.ksoftware.net/support/solutions/articles/232500-what-are-the-differences-between-ov-and-ev-level-code-signing-certificates-)) so EV is not for us.

## Costs
- [ksoftware.net](https://www.ksoftware.net/code-signing-certificates/)
  - OV 1 year - $84.00
  - OV 2 years - $79.50/yr
  - OV 3 years - $69.66.00/yr
- [thesslstore.co.uk](https://www.thesslstore.co.uk/products/code-signing-certificates.aspx)
  - Comodo (OV) - £58.32/yr
  - Sectigo* (OV) - £58.32/yr
  - DigiCert (OV) - £286.43/yr
- other places TBD

`*` Sectigo was formerly Comodo. Note sure why `thesslstore.co.uk` is offering both.

**Comment by ashleyvega** [comment]
@barnabee @edd Who can spend some :moneybag: to get a software-signing certificate?

**Comment by edd** [comment]
> @barnabee @edd Who can spend some :moneybag: to get a software-signing certificate?

You can!

**Comment by ashleyvega** [comment]
I have added credentials for https://www.thesslstore.co.uk/ in 1Password under `the SSL store`. Also in there are:
* CSR (Subject: C=GI, ST=Gibraltar, L=Gibraltar, O=Globalsky Labs Limited, emailAddress=hi@vega.xyz)
* private key (2048bit RSA)

**Comment by ashleyvega** [comment]
Current status: Due to a typo on my part, thesslstore/Sectigo are taking a long time to verify. Waiting for @jambone23 to provide company details.
